---
title: "Lecture 20: Twitter Data"
author: "Albert Y. Kim"
date: "November 9, 2016"
output: ioslides_presentation
---

<style>
h2 { 
 color: #3399ff;		
}
h3 { 
 color: #3399ff;		
}
slides > slide.backdrop {
  background: white;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(tidyr)
```



## Mining Twitter Data

[Beer vs church map](http://www.floatingsheep.org/2012/07/church-or-beer-americans-on-twitter.html)

What is the **most** important thing to keep in mind when observing such maps?



## Mining Twitter Data

**Strong** selection biases at every step:

> * Who signs up to Twitter
> * Who tweets at all
> * Who tweets about these topics
> * Who lets their location be revealed

i.e. the sample is non-random, so it is not representative of the population as
a whole, and hence the results of the sample are not generalizable to the
entire US population.

But there is still useful info nonetheless.



## API

Wikipedia: In computer programming, an **application programming interface**
(API) is a set of routines, protocols, and tools for building software and
applications.

So for example, if you want to build an App that uses Google Maps, Twitter, FB,
Instagram etc. data, you access their data via an API.



## API Keys

Wikipedia: An API key is a code passed in by computer programs calling an API to
identify the calling program, its developer, or its user to the Web site.

API keys are used to track and control how the API is being used, for example to
prevent malicious use or abuse of the API.



## Obtaining a Twitter API Key

We are getting digital permission to open the Twitter pipeline for our use, just
like any other developer would.
