---
title: "Lecture 17: Shiny Server"
author: "Albert Y. Kim"
date: "October 31, 2016"
output: ioslides_presentation
---

<style>
h2 { 
 color: #3399ff;		
}
h3 { 
 color: #3399ff;		
}
slides > slide.backdrop {
  background: white;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(tidyr)
```





## Publishing Apps

To publish your apps online you have two options: 

> * Go to [https://www.shinyapps.io/](https://www.shinyapps.io/) and create a free
account. You can host up to 5 shiny apps. However, you only get limited server
resources dedicated to each user.
> * Even better: Use the recently installed Middlebury Shiny Server Pro.





## Publishing Apps

Example (note the URL path): <a href = "https://shiny.middlebury.edu:3838/aykim/babynames/" target = "_blank">https://shiny.middlebury.edu:3838/aykim/babynames/</a>



## Publishing Apps

Today we will publish the Shiny App from HW-2 `HW-2_Shiny_App.Rmd` onto `shiny.middlebury.edu`




## Uploading to Middlebury Shiny Server

You need to be on campus or on VPN:

* Mac:
    + Open Finder
    + Menu Bar -> Go > Connect to Server: `cifs://shiny.middlebury.edu/YOUR_USERNAME`
* Windows:
    + Open File Explorer
    + In address bar, `\\shiny.middlebury.edu\YOUR_USERNAME`



## Uploading to Midd Shiny Server

Once logged in:

* Go into the folder `ShinyApps`
* Create a folder and call it `testing`
* Upload your `HW-2_Shiny_App.Rmd` Shiny app and rename it `index.Rmd`
* Your Shiny App is now available at  [https://shiny.middlebury.edu:3838/USERNAME/testing/](https://shiny.middlebury.edu:3838/aykim/testing/)




## Installing Packages

I've had a large number of commonly used R packages installed on Shiny Server (`tidyverse`, many dataset packages), but if you ever need to install one yourself.

1. Login to R on Shiny Server via command line
    + RStudio menu bar -> Tools -> Shell...
    + Type `ssh YOUR_USERNAME@shiny.middlebury.edu`
    + Type `R`.
1. Install package in R via command line
    + Type `install.packages("ggplot2")` for example
    + Select a CRAN mirror in the United States.
    + Say yes to prompts about installing in a new library.
