---
title: "Lecture 08: Shiny Apps"
author: "Albert Y. Kim"
date: "September 30, 2016"
output: ioslides_presentation
---

<style>
h2 { 
 color: #3399ff;		
}
h3 { 
 color: #3399ff;		
}
slides > slide.backdrop {
  background: white;
}
</style>


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(tidyr)
```



## Intro to Shiny

Today we will create **interactive** web applications via Shiny.  Shiny allows
you to do so without knowing HTML, JavaScript, CSS, etc. Only a little R.



## Shiny Approaches

There are many approaches to create a Shiny App:

> 1. **R Markdown**: New File -> R Markdown... -> Shiny -> either a document or slides. Today's focus!
> 1. **Single File App**: New File -> Shiny Web App -> Single File `app.R`
> 1. **Multiple File App**: Allows a more split organization. New File -> Shiny Web
App -> Multiple File `ui.R`/`server.R`



## Shiny Approaches

> * The 2nd and 3rd approach are more powerful, but more complicated.
> * We focus on the 1st, which is simplest.



## Test Drive

* File -> New File -> R Markdown...
* Shiny -> Set Title as "Testing"
* Click "Run Document"



## Components

1. **Inputs**: `inputPanel()`s that involve `somethingInput`. Ex: 
    + `selectInput()`: Drop down menu
    + `sliderInput()`: Slider
    + `textInput()` and more.
2. **Outputs**: `renderSomething()`s that display outputs. Ex:
    + `renderPlot()`: plots
    + `renderTable()`: tables




## Back to Code

* On lines 22-28, we gather the **inputs**
    + The `selectInput()` drop down menu value gets assigned to `n_breaks`
    + The `sliderInput()` slider value gets assigned to `bw_adjust`
* On lines 30-36, we render the **outputs**
    + Specifically a `renderPlot` using a base R `hist()`ogram
    + Note how we access the inputed values as `input$n_breaks` and `input$bw_adjust`




## Input/Output Options 

* From RStudio -> Help -> Cheatsheets -> Shiny Web Applications
    + **Inputs**: Column on right of 1st page
    + **Outputs**: All the `renderSomething()`'s in bottom of middle section on 1st page
* See Help files. Ex: Type `?shiny::passwordInput`




## Today's Exercise

Using the `babynames` dataset in the `babynames` package, modify `Testing.Rmd` so that we can

* type in a name
* specify a range of years

And get a `ggplot` plot of the proportions of babies with the specified name for the specified range of years.




## Today's Exercise

This is a **software engineering** project. There are best practices for such things:

* **Start simple**: get the simplest possible version of your project working
* **Then Iterate**: then slowly start adding components, testing often

Don't try to get it perfect from the beginning!




